version: "3"
services:
  #application service
  php:
    image: nagarajc/laravel:latest
    container_name: laravel-app
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    ports:
      - "9000:9000"

  artisan:
    image: nagarajc/laravel:latest
    container_name: laravel-artisan
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
          php artisan migrate
          php artisan optimize
    depends_on:
      - php
    networks:
      - laravel

  #web server service
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      - php

#network settings
networks:
  laravel:
    driver: bridge
