version: "3"
services:
  #application service
  php:
    image: nagarajc/laravel:latest
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    command: php artisan optimize
    networks:
      - laravel
  
  #web server service
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      - php

#network settings
networks:
  laravel:
    driver: bridge


