version: "3"
services:

  #application service
  php:
    image: nagarajc/laravel:latest
    container_name: laravel-app
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - laravel
    ports:
      - "9000:9000"

  #Database migration service
  composer:
    image: nagarajc/laravel:latest
    container_name: laravel-composer-install
    working_dir: /var/www/
    volumes:
      - ./src:/var/www:delegated
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
          composer install
    depends_on:
      - php
    networks:
      - laravel

  #Database migration service
  artisan:
    image: nagarajc/laravel:latest
    container_name: laravel-artisan
    working_dir: /var/www/
    volumes:
      - ./src:/var/www:delegated
    entrypoint: ["/bin/bash", "-c"]
    command: 
      - |
          php artisan migrate
          php artisan optimize
    depends_on:
      - php
      - composer
    networks:
      - laravel

  

  #web server service
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    working_dir: /var/www/
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./dockercompose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      - php

#network settings
networks:
  laravel:
    driver: bridge

