name: Publish Docker image on docker hub
on:
  push:
    branches:
    - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #build start
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Setup docker builder
      uses: docker/setup-buildx-action@v3

    - name: build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.DOCKERHUB_USERNAME }}/laravel:latest


